export {default as Home } from './Home'
export {default as About } from './About'
export {default as Navbar } from './Navbar'
export {default as Contact } from './Contact'
export {default as Faq } from './Faq'
export {default as SignIn } from './SignIn'
export {default as SignUp } from './SignUp'
