export {default as Home } from './pages/Home'
export {default as About } from './pages/About'
export {default as Navbar } from './Navbar'
export {default as Contact } from './pages/Contact'
export {default as Faq } from './pages/Faq'
export {default as SignIn } from './pages/SignIn'
export {default as SignUp } from './pages/SignUp'
export {default as Footer } from './Footer'
